import Link from "next/link";
import { CTA } from "@/components/site/CTA";
import { PageHero } from "@/components/site/PageHero";
import { Breadcrumbs, FaqSection, JsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/site/Seo";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Planos e precos do Shamar PDV", "Entenda Single, Network e piloto assistido do Shamar PDV sem valores inventados, com proposta comercial sob consulta.", "/precos");

const crumbs = [{ name: "Inicio", href: "/" }, { name: "Precos", href: "/precos" }];
const faqs = [
  { question: "Por que os valores estao sob consulta?", answer: "Porque implantacao, migracao, quantidade de caixas e validacao de perifericos mudam o escopo comercial. A proposta evita surpresa." },
  { question: "Qual a diferenca entre Single e Network?", answer: "Single atende operacao local em uma instalacao. Network atende caixas em rede local com dados centralizados localmente." },
  { question: "Piloto assistido e obrigatorio?", answer: "Ele e o caminho recomendado quando existe migracao, hardware ou rotina que precisa de validacao antes de ampliar." }
];

export default function PrecosPage(){return <main><JsonLd id="breadcrumb-precos" data={breadcrumbJsonLd(crumbs)} /><JsonLd id="faq-precos" data={faqJsonLd(faqs)} /><PageHero eyebrow="Planos e precos" title="Escolha o caminho certo sem surpresa comercial." text="Sem preco inventado: a pagina explica para quem serve cada caminho e leva para uma proposta baseada no tamanho da loja, migracao e perifericos."/><section className="section compactTop"><Breadcrumbs items={crumbs} /><p className="lead intentText">Para buscas como sistema PDV para loja, PDV offline, atacado e varejo, controle de estoque e migracao de PDV.</p></section><section className="section grid cols3"><article className="card"><h3>Single</h3><p>Para loja que precisa de PDV local, caixa rapido, produtos, estoque, clientes, compras, historico e backup.</p><ul><li>Operacao local</li><li>Venda e caixa</li><li>Backup e restauracao</li></ul><strong>Sob consulta</strong></article><article className="card"><h3>Network</h3><p>Para operacao com mais de um caixa em rede local e persistencia PostgreSQL.</p><ul><li>Caixas em rede</li><li>Dados centralizados localmente</li><li>Mesma autoridade comercial</li></ul><strong>Sob consulta</strong></article><article className="card"><h3>Piloto assistido</h3><p>Para validar implantacao, migracao, rotinas, backup e perifericos disponiveis antes de ampliar.</p><ul><li>Checklist de entrada</li><li>Migracao analisada</li><li>Smoke operacional</li></ul><strong>Sob consulta</strong></article></section><section className="section split"><div><p className="eyebrow">Depois do contato</p><h2>A proposta nasce da operacao real.</h2><p className="lead">Levantamos quantidade de caixas, tipo de loja, cadastros a migrar, perifericos e se o melhor caminho inicial e Single, Network ou piloto assistido.</p></div><div className="card"><h3>Paginas relacionadas</h3><div className="routeLinks"><Link className="button secondary" href="/produto">Produto</Link><Link className="button secondary" href="/migracao">Migracao</Link><Link className="button secondary" href="/compatibilidade">Compatibilidade</Link></div></div></section><FaqSection items={faqs} /><CTA label="Receber proposta" source="precos" /></main>}
