import Link from "next/link";
import { CTA } from "@/components/site/CTA";
import { PageHero } from "@/components/site/PageHero";
import { Breadcrumbs, FaqSection, JsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/site/Seo";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Migração de sistema PDV sem começar do zero", "Troque de sistema PDV com análise de origem, importação segura de produtos, clientes, fornecedores, estoque e preços quando os dados permitem.", "/migracao");

const crumbs = [{ name: "Início", href: "/" }, { name: "Migração", href: "/migracao" }];
const faqs = [
  { question: "Posso migrar produtos e clientes do sistema antigo?", answer: "Sim, quando a origem tem dados confiáveis. A migração preserva identidade externa ou documento quando isso é seguro." },
  { question: "O Shamar importa qualquer sistema automaticamente?", answer: "Não. CSV, XML e adaptadores entram por pipeline controlado; origem ambígua vai para revisão em vez de chute." },
  { question: "Nome do cliente sozinho identifica cadastro?", answer: "Não. Nome sozinho não é usado como identidade automática para evitar duplicidade e erro comercial." }
];

export default function MigracaoPage(){return <main><JsonLd id="breadcrumb-migracao" data={breadcrumbJsonLd(crumbs)} /><JsonLd id="faq-migracao" data={faqJsonLd(faqs)} /><PageHero eyebrow="Migração" title="Você não precisa recadastrar tudo na mão para conhecer o Shamar." text="A migração reaproveita dados factuais, revisa o que estiver ambíguo e evita importação cega. O objetivo é entrar em operação com segurança, não prometer mágica sobre qualquer legado." cta="Quero avaliar minha migração" ctaHref="/contato?origem=migracao"/><section className="section compactTop"><Breadcrumbs items={crumbs} /><p className="lead intentText">Ideal para quem procura migrar sistema PDV, trocar cadastro de produtos, preservar clientes e reduzir medo de parada na implantação.</p></section><section className="section grid cols3"><div className="card"><h3>Produtos, códigos e estoque</h3><p>Produtos, unidades, códigos, preços e estoque podem ser migrados quando a origem fornece dados confiáveis e rastreáveis.</p></div><div className="card"><h3>Clientes e fornecedores</h3><p>Usamos identidade externa ou documento quando a origem permite. Dados incertos ficam visíveis para revisão.</p></div><div className="card"><h3>Pipeline controlado</h3><p>CSV, XML e adaptadores específicos passam por preparação, validação e relatório, sem gravar dados duvidosos em silêncio.</p></div></section><section className="section split"><div><p className="eyebrow">Próximo passo</p><h2>Antes de trocar, entendemos a origem.</h2><p className="lead">A conversa comercial identifica sistema atual, volume de cadastros, necessidade de estoque, periféricos e prazo de entrada.</p></div><div className="card"><h3>Páginas relacionadas</h3><div className="routeLinks"><Link className="button secondary" href="/segmentos/autopecas?origem=migracao">Autopeças</Link><Link className="button secondary" href="/compatibilidade?origem=migracao">Compatibilidade</Link><Link className="button secondary" href="/demonstracao?origem=migracao">Agendar demonstração</Link></div></div></section><FaqSection items={faqs} /><CTA label="Falar com vendas" source="migracao" /></main>}
